# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiles',
            name='celular',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
    ]
