# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['area', 'nombre']},
        ),
        migrations.AlterModelOptions(
            name='solicitud',
            options={'ordering': ['fecha_solicitud', 'hora_solicitud']},
        ),
        migrations.AlterField(
            model_name='area',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(max_length=400),
        ),
    ]
