# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0003_auto_20170302_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actualizacion',
            name='href',
        ),
        migrations.RemoveField(
            model_name='actualizacion',
            name='texto',
        ),
        migrations.RemoveField(
            model_name='actualizacion',
            name='titulo',
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='href_Actualizacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='href_Categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='href_Enlace',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='href_Testigo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='texto_Actualizacion',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='titulo_Actualizacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='titulo_Categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='titulo_Enlace',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='titulo_Testigo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
