# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0006_auto_20170306_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacion',
            name='testigo_profission',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='informacion',
            name='testigo_autor',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
    ]
