# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0007_auto_20170306_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitud',
            options={'ordering': ['usuario', 'fecha_solicitud', 'hora_solicitud']},
        ),
        migrations.AlterField(
            model_name='informacion',
            name='video_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='galeria'),
        ),
    ]
